(require 'my-rails)
(require 'rdoc-mode)
(require 'ruby-testing)

(defun insert-ruby-hash-arrow ()
  (interactive "*")
  (insert "=>")
  (backward-char 2)
  (just-one-space)
  (forward-char 2)
  (just-one-space))

(add-hook 'ruby-mode-hook
          (lambda ()
            (define-key ruby-mode-map "\r" 'newline-and-indent)
            (define-key ruby-mode-map "\M-\C-h" 'backward-kill-word)
            (define-key ruby-mode-map "\C-cr" 'executable-interpret)
            (define-key ruby-mode-map "\C-cd" 'debug-comment)
            (define-key ruby-mode-map "\C-ch" 'insert-ruby-hash-arrow)
            (define-key ruby-mode-map "\C-ct" 'run-ruby-test)
            (define-key ruby-mode-map "\C-cs" 'run-ruby-spec)
            (define-key ruby-mode-map "{" 'self-insert-command)
            (define-key ruby-mode-map "}" 'self-insert-command)
            (setq ruby-indent-level 2)
            (font-lock-mode 1)))

(provide 'my-ruby-mode)
